version: "3.0"
services:
  dockerapp:
    image: saidmb/dockerapp
    ports:
      - "5000:5000"
    depends_on:
      - redis
    deploy:
      replicas: 3
  redis:
    image: redis:3.2.0
  visualizer:
    image: saidmb/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
       placement:
          constraints:
             - node.role == manager
